language: ruby
rvm:
- 2.4.4
sudo: required
dist: xenial

services:
  - mysql
  - docker
  - memcached
  - redis-server

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE sashimi_test;'

install:
  - travis_retry bundle install  
  - curl -sL https://sentry.io/get-cli/ | bash
  - sentry-cli --version

before_script:
  - memcached -p 11211 &
  - cp .env.travis .env
  - mkdir -p tmp/pids
  - mkdir -p log
  - bundle exec rake db:setup RAILS_ENV=test

script:
  - bundle exec rspec
  - bundle exec codeclimate-test-reporter

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - REPO=datacite/sashimi;
  - export AUTHOR_NAME="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
  - AUTO_DEPLOY=false;
  - if [ "${TRAVIS_TAG?}" ]; then
      docker build -f Dockerfile -t $REPO:$TRAVIS_TAG .;
      docker push $REPO:$TRAVIS_TAG;
      echo "Pushed to" $REPO:$TRAVIS_TAG;
      AUTO_DEPLOY=true;
    elif [ "$TRAVIS_BRANCH" == "master" ]; then
      docker build -f Dockerfile -t $REPO .;
      docker push $REPO;
      echo "Pushed to" $REPO;
      AUTO_DEPLOY=true;
    elif [ "$TRAVIS_PULL_REQUEST" == "true" ]; then
      docker build -f Dockerfile -t $REPO:$TRAVIS_PULL_REQUEST_BRANCH .;
      docker push $REPO:$TRAVIS_PULL_REQUEST_BRANCH;
      echo "Pushed to" $REPO:$TRAVIS_PULL_REQUEST_BRANCH;
      AUTO_DEPLOY=true;
    else
      docker build -f Dockerfile -t $REPO:$TRAVIS_BRANCH .;
      docker push $REPO:$TRAVIS_BRANCH;
      echo "Pushed to" $REPO:$TRAVIS_BRANCH;
      AUTO_DEPLOY=true;
    fi

  - if [ "$AUTO_DEPLOY" == "true" ]; then
      wget https://github.com/jwilder/dockerize/releases/download/v0.6.0/dockerize-linux-amd64-v0.6.0.tar.gz;
      tar -xzvf dockerize-linux-amd64-v0.6.0.tar.gz;
      rm dockerize-linux-amd64-v0.6.0.tar.gz;
      export GIT_SHA=$(git rev-parse --short HEAD);
      export GIT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1));
      git clone "https://${TRAVIS_SECURE_TOKEN}@github.com/datacite/mastino.git";
      ./dockerize -template vendor/docker/_sashimi.auto.tfvars.tmpl:mastino/stage/services/metrics-api/_sashimi.auto.tfvars;
      
      cd mastino;
      git remote;
      git config user.email ${DOCKER_EMAIL};
      git config user.name ${DOCKER_USERNAME};
      
      if [ "${TRAVIS_TAG?}" ]; then
        git add prod-eu-west/services/metrics-api/_sashimi.auto.tfvars;
        git add test/services/metrics-api/_sashimi.auto.tfvars;
        git commit -m "${AUTHOR_NAME} Adding sashimi git variables for commit tagged ${TRAVIS_TAG?}";
        git push "https://${TRAVIS_SECURE_TOKEN}@github.com/datacite/mastino.git" master;
      elif [ "$TRAVIS_PULL_REQUEST" == "true" ]; then
        git add stage/services/metrics-api/_sashimi.auto.tfvars;
        git commit -m "Adding sashimi git variables for pull request ${TRAVIS_PULL_REQUEST}";
        git push "https://${TRAVIS_SECURE_TOKEN}@github.com/datacite/mastino.git" ${TRAVIS_PULL_REQUEST_BRANCH};
      else
        git add stage/services/metrics-api/_sashimi.auto.tfvars;
        git commit -m "Adding sashimi git variables for latest commit";
        git push "https://${TRAVIS_SECURE_TOKEN}@github.com/datacite/mastino.git" master;
      fi
    fi

notifications:
  slack: datacite:Wt8En0ALoTA6Kjc5EOKNDWxN
  email: false
