=begin
METRICS API

The SASHIMI API represents a RESTful implementation of SUSHI automation intended to returns COUNTER Research Data Release 1 reports 

OpenAPI spec version: 1.0.0
Contact: support@datacite.org
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class PublishersController < ApplicationController

  # include validation methods for sushi
  include Cacheable


  def index
    response = {
      "total" => cached_client_count,
    }

    render json: response, status: :ok
  end

  def destroy
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def show
    response = {
      "client-id" => params[:id],
      "total" => cached_reports_count(params[:id]),
      "created-by" => cached_created_by_count(params[:id]),
      "year" => cached_year_count(params[:id]),
      "report-types" => cached_report_id_count(params[:id]),
    }

    render json: response, status: :ok
  end

  def update
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
