=begin
METRICS API

The SASHIMI API represents a RESTful implementation of SUSHI automation intended to returns COUNTER Research Data Release 1 reports 

OpenAPI spec version: 1.0.0
Contact: support@datacite.org
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class ErrorModel < ApplicationRecord
  validates_presence_of :code
  validates_presence_of :severity
  validates_presence_of :message

end
