=begin
METRICS API

The SASHIMI API represents a RESTful implementation of SUSHI automation intended to returns COUNTER Research Data Release 1 reports

OpenAPI spec version: 1.0.0
Contact: support@datacite.org
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'base32/url'

class Report < ApplicationRecord

  # include validation methods for sushi
  include Metadatable

  # include validation methods for sushi
  include Queueable 

  attr_accessor :month, :year
  validates_presence_of :report_id, :created_by, :report_datasets, :client_id, :provider_id, :created, :reporting_period
  validates :uid, uniqueness: true
  validates :validate_sushi, sushi: {presence: true}

  serialize :exceptions, Array
  before_create :set_id
  before_validation :set_uid, on: :create
  after_create :push_report


  def push_report
    puts "******** to queue"
    logger.warn "calling queue for " + uid
    queue_report if ENV["AWS_REGION"]
  end

  private

  # random number that fits into MySQL bigint field (8 bytes)
  def set_id
    self.id = SecureRandom.random_number(9223372036854775807)
  end

  def set_uid
    unless reporting_period.nil? 
      puts reporting_period.to_json
      month = Date.strptime(reporting_period["begin_date"],"%Y-%m-%d").month.to_s 
      year = Date.strptime(reporting_period["begin_date"],"%Y-%m-%d").year.to_s 
      write_attribute(:month,  month ) 
      write_attribute(:year,  year) 
    end
    self.uid = "#{year}-#{month}-#{created_by}"
  end
end
