name: Deploy to staging
on:
  push:
    branches:
      - "master"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    uses: ./.github/workflows/build_docker.yml
    with:
      image: ghcr.io/${{ github.repository }}web
      dockerfile: ./Dockerfile

  deploy:
    needs: [test, build]
    uses: ./.github/workflows/deployment.yml
    with:
      versionvar_filename: sashimi
      service_name: metrics-api
      env_name: stage
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
