name: Deploy to staging
on:
  push:
    branches:
      - "master"
  workflow_dispatch:
    inputs:
      deploy_ref:
        description: "Branch, tag, or SHA to deploy to staging"
        required: true
        default: "master"

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      ref: ${{ github.event_name == 'workflow_dispatch' && inputs.deploy_ref || github.ref_name }}
    secrets: inherit

  build:
    needs: test
    uses: ./.github/workflows/build_docker.yml
    with:
      image: ghcr.io/${{ github.repository }}
      dockerfile: ./Dockerfile
      ref: ${{ github.event_name == 'workflow_dispatch' && inputs.deploy_ref || github.ref_name }}

  deploy:
    needs: [test, build]
    uses: ./.github/workflows/deployment.yml
    with:
      versionvar_filename: _sashimi
      service_name: metrics-api
      env_name: stage
      ref: ${{ github.event_name == 'workflow_dispatch' && inputs.deploy_ref || github.ref_name }}
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
