name: Release

on:
  release:
    types: [published]

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  build:
    needs: test
    uses: ./.github/workflows/build_docker.yml
    with:
      image: ghcr.io/${{ github.repository }}
      dockerfile: ./Dockerfile

  deploy:
    needs: [test, build]
    uses: ./.github/workflows/deployment.yml
    with:
      versionvar_filename: _sashimi
      service_name: metrics-api
      env_name: prod-eu-west
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  deploy-test:
    needs: [test, build]
    uses: ./.github/workflows/deployment.yml
    with:
      versionvar_filename: _sashimi
      service_name: metrics-api
      env_name: test
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
