name: Test workflow

on:
  workflow_call:
    secrets:
      SECRET_KEY_BASE:
        required: true
      SESSION_ENCRYPTED_COOKIE_SALT:
        required: true
      JWT_PRIVATE_KEY:
        required: true
      JWT_PUBLIC_KEY:
        required: true
      MDS_USERNAME:
        required: true
      MDS_PASSWORD:
        required: true
      AWS_REGION:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      memcached:
        image: memcached:1.4.31
        ports:
          - 11211/udp
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: metrics_test
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306
      redis:
        image: redis:6
        ports:
          - 6379:6379
    env:
      MEMCACHE_SERVERS: "localhost:11211"
      MYSQL_HOST: "127.0.0.1"
      MYSQL_DATABASE: metrics_test
      MYSQL_USER: root
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
      SESSION_ENCRYPTED_COOKIE_SALT: ${{ secrets.SESSION_ENCRYPTED_COOKIE_SALT }}
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
      MDS_USERNAME: ${{ secrets.MDS_USERNAME }}
      MDS_PASSWORD: ${{ secrets.MDS_PASSWORD }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 3.1.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          cp .env.build .env
          gem install rubygems-update -v 3.5.6
          gem install bundler:2.5.6
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          sudo /etc/init.d/mysql start
          bundle exec rails db:setup RAILS_ENV=test
      - name: Test
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
          MEMCACHE_SERVERS: "localhost:11211"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: 'metrics-api.stage.datacite.org'
        run: |
          bundle exec rspec
          echo $?